version: "3.2"
services:
  postgres:
    image: "postgres:9.6-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nsc
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    volumes:
      - "./postgres_initdb:/docker-entrypoint-initdb.d:ro"
    networks:
      - postgres

networks:
  postgres:
