version: 2

workflows:
  version: 2
  test_and_release:
    jobs:
      - compute_tag:
          filters:
            branches:
              only:
                - master
                - production

      - test_and_make

      - build_container:
          filters:
            branches:
              only:
                - master

          requires:
            - compute_tag
            - test_and_make

      - deploy_image:
          filters:
            branches:
              only:
                - master
          requires:
            - build_container
            - compute_tag

jobs:
  test_and_make:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - $HOME/.npm
      - run:
          command: |
            set -e
            npm run fmt:check
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  build_container:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Push backend image to registry
          command: |
            set -e
            TAG="$(cat tag.txt)"
            TAG=$TAG docker build -t gcr.io/x-cycling-251008/nsc:$TAG .
            echo $GCLOUD_SERVICE_KEY | docker login -u _json_key --password-stdin gcr.io/x-cycling-251008
            docker tag "gcr.io/x-cycling-251008/nsc:${TAG}" "gcr.io/x-cycling-251008/nsc:latest"
            docker push "gcr.io/x-cycling-251008/nsc:latest"
            docker push "gcr.io/x-cycling-251008/nsc:${TAG}"

  deploy_image:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            set -e
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project x-cycling-251008
            TAG="$(cat tag.txt)" bash deploy.sh
        
  compute_tag:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: echo "$(git rev-parse --short HEAD)" > tag.txt
      - persist_to_workspace:
          root: .
          paths:
            - tag.txt
